channels:
  - conda-forge
dependencies:
  - python=3.12
  - cudatoolkit
  - setuptools
  - wheel
  - pip
  - pip:
      - lightning==2.5.2
      - fire>=0.7.0
      - shapely==2.0.6
      - pillow>=10.4.0
      - matplotlib>=3.9.2
      - setuptools
      - numpy
      - pillow>=10.4.0
      - tensorboard>=2.20.0
      - tensorboardx>=2.6.4
      - torch==2.10.0
      - torchvision==0.25.0
      - scikit-learn==1.4.2
      - mediapipe==0.10.18
      - torchmetrics==1.5.1
      - typing_extensions==4.12.2
      - joblib==1.4.2
      - imblearn==0.0
      - imbalanced-learn==0.12.3
      - optuna==4.1.0
      - shap==0.46.0
      - plotly==5.24.1
      - dash==2.18.2
      - dash-bootstrap-components==1.7.1
      - cleanvision==0.3.6
      - seaborn==0.13.2
      - captum==0.8.0
      - scipy>=1.14.1
      - pandas>=2.2.3
      - fire>=0.7.0
      - loguru>=0.7.3
      - tqdm>=4.67.0
      - pronto==2.5.8
      - trimesh>=4.5.3
      - onnxruntime==1.24.2
      - onnx==1.20.1
      - onnxscript==0.6.2
      - onnxoptimizer==0.4.2
      - onnx_ir==0.2.0